import './style.css'
import './load.js'
import './script.js'
import './assets/logo.png'
import './assets/back.webp'
import './assets/back1.jpg'
import './assets/kurtted.gif'
import './assets/illarionz.jpg'